### ISSUE TITLE
Any reason for not having an index.ts or mod.ts file for all imports

### ISSUE THREAD

**Issue by borsemayur2** [crewdevio/snel-carbon#2]
Importing components in following way is bit tedious. Should we use an index.ts or mod.ts file to import any component from that file?
![image](https://user-images.githubusercontent.com/47341981/129998900-7707ecf9-cc93-4acc-af4e-8a4d7d719301.png)

**Comment by buttercubz** [comment]
the reason is that drollup has problems compiling the components when they are exported by a common file.

although you can extend the import map files of the components and the icons in the snel.config file

https://github.com/crewdevio/Snel#snel-config-file
